### ISSUE TITLE
Disjoined and unaligned KeyUpdate msgs are not rejected.

### ISSUE THREAD

**Issue by NoName115** [tlsfuzzer/tlslite-ng#342]
When the KeyUpdate msg is fragmented into 2 parts, and app_data are sent between them.
Tlslite-ng doesn't reject this conversation with `unexpected_message` alert.
For a discussion see https://github.com/tomato42/tlsfuzzer/pull/501#pullrequestreview-197563625

**Comment by tomato42** [comment]
and in general, there are no checks to verify that the messages are aligned with record boundary, so it requires a bit more complex fix
