### ISSUE TITLE
Support compressed_certificate

### ISSUE THREAD

**Issue by ghost** [tlsfuzzer/tlslite-ng#431]
Hi there! Im in need of the compressed certificate extension, is this something that could be supported or is it in work?

- Thanks

**Comment by tomato42** [comment]
If somebody implements it, sure, it could be supported and would be welcome. But it's not a priority for me now.

**Comment by BRK0014** [comment]
> If somebody implements it, sure, it could be supported and would be welcome. But it's not a priority for me now.

That would be dope, do you know if fuzzer has it?

**Comment by tomato42** [comment]
no, it doesn't

**Comment by tomato42** [comment]
Fixed with #521
