### ISSUE TITLE
Example tls server supporting both SRP and ClientAuth

### ISSUE THREAD

**Issue by grindsa** [tlsfuzzer/tlslite-ng#468]
Hi,

I would like to setup a `tls.py`server which allows to authenticate by using either SRP or client certificate.

I am starting the server with the following command.

```
py .\scripts\tls.py server -v .\scripts\est_proxy.db -k .\certs\srv.key.pem -c .\certs\srv.crt.pem 0.0.0.0:1443
```

Authentication via SRP works fine but connections using a certificate-based handshare get aborted with the message 
`Unable to negotiate mutually acceptable parameters`

Client authentication works btw fine with I start the server without -v parameter.

Any idea what I am doing wrong? Any hint how to troubleshoot this further?

Thank you for your help

/G.

**Comment by tomato42** [comment]
Looks like the server handshake implementation considers SRP and cert-based authentication to be mutually exclusive:
https://github.com/tlsfuzzer/tlslite-ng/blob/d59ac46a9bfe217934611e79552cc6aef861586c/tlslite/tlsconnection.py#L3375-L3406

but it also considers that if SRP and certificate is configured, that the intention is to have a server that uses the combined SRP and RSA authentication, like the TLS_SRP_SHA_RSA_WITH_AES_128_CBC_SHA.

Changing those `elif`s to `if`s may make it possible to configure a server that supports all the different configurations at the same time, but I worry we don't have good enough test coverage to ensure this doesn't have an unintended side-effect (like ciphersuite that shouldn't get enabled gets enabled) for specific configurations.

**Comment by grindsa** [comment]
Thank you for your answer.  The above change worked fine and should be good enough for me.
