### ISSUE TITLE
Lack of check for some messages' Record Version field

### ISSUE THREAD

**Issue by SmallTown123** [tlsfuzzer/tlslite-ng#490]
The tlslite-ng server continues to respond normally to an ApplicationData or EncryptedFinishMessage in the third handshake with the not expected **Record Version**, and without any Alert messages.
Even if we send the above two messages containing a random Record Version, the server still responds normally.

This is caused by the lack of record version detection for this field.

It is uncertain whether there is a potential security risk.

**Comment by tomato42** [comment]
> It is uncertain whether there is a potential security risk.

there isn't, the record protection is calculated from the expected protocol version, not the one transferred on the wire, so the attacker can't substitute record from one version into a session with another version

**Comment by SmallTown123** [comment]
Ok, I understand, thank you for your reply!
