### ISSUE TITLE
Session tickets support [TLS 1.2]

### ISSUE THREAD

**Issue by tomato42** [tlsfuzzer/tlslite-ng#60]
Add support for [RFC 4507](http://tools.ietf.org/html/rfc4507)

**Comment by FiachAntaw** [comment]
FYI RFC 4507 is obsoleted by [RFC 5077](https://www.ietf.org/rfc/rfc5077.txt).

**Comment by tomato42** [comment]
If there are any differences in there, support for both will be needed (for tlsfuzzer's sake)

**Comment by tomato42** [comment]
see also #287

**Comment by martyur** [comment]
Is this actively being worked on ? Have an issue where I need session ticket extension support on the client side for TLS 1.2 and unfortunately this is currently not supported.
Really appreciate the work you're doing here lads.

**Comment by tomato42** [comment]
> Is this actively being worked on?

no, I don't think @inikolcev is working on this at the moment

**Comment by inikolcev** [comment]
@tomato42 @martyur I don't actively work on it, but I'm planning to work on it in the next couple of months

**Comment by BRK0014** [comment]
Any idea when this will come? our project is really in need of Session ticket extension on client side

**Comment by BRK0014** [comment]
@inikolcev 

bump

**Comment by inikolcev** [comment]
> Any idea when this will come? our project is really in need of Session ticket extension on client side

I have already done most of the work and I should be able to finish everything in the next 1-2 weeks I think.

**Comment by BRK0014** [comment]
> > Any idea when this will come? our project is really in need of Session ticket extension on client side
> 
> I have already done most of the work and I should be able to finish everything in the next 1-2 weeks I think.

That sounds great man! Thanks for all the hard work, we appreciate it! looking forward

**Comment by ZeddYu** [comment]
Hi. I also need the ticket session support. Have it been merged to the master?

**Comment by tomato42** [comment]
no, the work is happening in PR #437

**Comment by tomato42** [comment]
I consider the work in #437 to be final (modulo review) and feature complete.
If you're still interested in it, I would welcome information if you've tested it.
